--
-- PostgreSQL database dump
--

\restrict 4JU2yXvzcD6begUTiHkBRAH0ivO9IYgT0nWQxevt3CdObmFWbYxRgSTMwCWPQR5

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AuditLog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AuditLog" (
    "Id" integer NOT NULL,
    "Username" character varying(50) NOT NULL,
    "Action" character varying(100) NOT NULL,
    "Details" text NOT NULL,
    "Timestamp" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public."AuditLog" OWNER TO postgres;

--
-- Name: AuditLog_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AuditLog" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AuditLog_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Client" (
    "Id" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "UserId" integer NOT NULL
);


ALTER TABLE public."Client" OWNER TO postgres;

--
-- Name: Client_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Client" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Client_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Employee" (
    "Id" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Role" text NOT NULL,
    "UserId" integer NOT NULL,
    "MaxActiveTickets" integer NOT NULL
);


ALTER TABLE public."Employee" OWNER TO postgres;

--
-- Name: Employee_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Employee" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Employee_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ExternalLink; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ExternalLink" (
    "Id" integer NOT NULL,
    "TicketId" integer NOT NULL,
    "System" integer NOT NULL,
    "ExternalId" character varying(200) NOT NULL,
    "ExternalKey" character varying(200),
    "Url" character varying(1000),
    "Direction" integer NOT NULL,
    "LastSyncedAt" timestamp without time zone,
    "ContentHash" character varying(200)
);


ALTER TABLE public."ExternalLink" OWNER TO postgres;

--
-- Name: ExternalLink_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ExternalLink" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ExternalLink_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Feedback; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Feedback" (
    "Id" integer NOT NULL,
    "TicketId" integer NOT NULL,
    "ClientId" integer NOT NULL,
    "SupportId" integer,
    "Comment" text NOT NULL,
    "Rating" integer NOT NULL,
    "CreatedAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public."Feedback" OWNER TO postgres;

--
-- Name: Feedback_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Feedback" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Feedback_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: IntegrationSettings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."IntegrationSettings" (
    "Id" integer NOT NULL,
    "System" integer NOT NULL,
    "BaseUrl" character varying(500) NOT NULL,
    "ProjectKey" character varying(100) NOT NULL,
    "BoardOrListId" character varying(200) NOT NULL,
    "AuthLogin" character varying(200) NOT NULL,
    "AuthSecret" character varying(2000) NOT NULL,
    "DefaultIssueType" character varying(100) NOT NULL,
    "DefaultPriority" character varying(50) NOT NULL
);


ALTER TABLE public."IntegrationSettings" OWNER TO postgres;

--
-- Name: IntegrationSettings_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."IntegrationSettings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."IntegrationSettings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: KnowledgeArticle; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."KnowledgeArticle" (
    "Id" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Content" text NOT NULL,
    "AuthorId" integer NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone NOT NULL,
    "ViewCount" integer DEFAULT 0 NOT NULL,
    "HelpfulCount" integer DEFAULT 0 NOT NULL,
    "NotHelpfulCount" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."KnowledgeArticle" OWNER TO postgres;

--
-- Name: KnowledgeArticle_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."KnowledgeArticle" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."KnowledgeArticle_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MlModelMetrics; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MlModelMetrics" (
    "Id" integer NOT NULL,
    "ModelType" character varying(50) NOT NULL,
    "TrainedAt" timestamp without time zone NOT NULL,
    "MicroAccuracy" double precision NOT NULL,
    "MacroAccuracy" double precision NOT NULL,
    "LogLoss" double precision NOT NULL,
    "SampleCount" integer NOT NULL
);


ALTER TABLE public."MlModelMetrics" OWNER TO postgres;

--
-- Name: MlModelMetrics_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."MlModelMetrics" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MlModelMetrics_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Notification" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Message" character varying(2000) NOT NULL,
    "Type" character varying(50) NOT NULL,
    "TicketId" integer,
    "CreatedAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "IsRead" boolean NOT NULL
);


ALTER TABLE public."Notification" OWNER TO postgres;

--
-- Name: NotificationSettings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."NotificationSettings" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "NotifyOnNewTickets" boolean NOT NULL,
    "NotifyOnStatusChanged" boolean NOT NULL,
    "NotifyOnComments" boolean DEFAULT true NOT NULL,
    "NotifyOnDueSoon" boolean NOT NULL,
    "DueSoonThresholdMinutes" integer NOT NULL,
    "PlaySound" boolean DEFAULT true NOT NULL,
    "ShowToast" boolean DEFAULT true NOT NULL,
    "EmailEnabled" boolean DEFAULT false NOT NULL
);


ALTER TABLE public."NotificationSettings" OWNER TO postgres;

--
-- Name: NotificationSettings_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."NotificationSettings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."NotificationSettings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Notification_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Notification" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Notification_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PasswordResetToken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PasswordResetToken" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Token" character varying(128) NOT NULL,
    "ExpiresAt" timestamp without time zone NOT NULL,
    "IsUsed" boolean NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL
);


ALTER TABLE public."PasswordResetToken" OWNER TO postgres;

--
-- Name: PasswordResetToken_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PasswordResetToken" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PasswordResetToken_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SearchPreset; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SearchPreset" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "TextQuery" character varying(500),
    "Status" character varying(50),
    "Category" integer,
    "Priority" integer,
    "CreatedFrom" timestamp without time zone,
    "CreatedTo" timestamp without time zone
);


ALTER TABLE public."SearchPreset" OWNER TO postgres;

--
-- Name: SearchPreset_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SearchPreset" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SearchPreset_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Solution; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Solution" (
    "Id" integer NOT NULL,
    "ResolutionText" text NOT NULL,
    "ResolutionDate" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "KnowledgeArticleId" integer,
    "TicketId" integer NOT NULL
);


ALTER TABLE public."Solution" OWNER TO postgres;

--
-- Name: Solution_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Solution" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Solution_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Ticket; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Ticket" (
    "Id" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" text NOT NULL,
    "Status" character varying(50) DEFAULT 'Open'::character varying NOT NULL,
    "Priority" integer NOT NULL,
    "Category" integer NOT NULL,
    "CreatedAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "DueAt" timestamp without time zone,
    "ClosedAt" timestamp without time zone,
    "AttachmentPath" character varying(500),
    "AttachmentFileName" character varying(255),
    "AttachmentContentType" character varying(100),
    "AttachmentSize" bigint,
    "AssigneeEmployeeId" integer,
    "ClientId" integer NOT NULL,
    "IsOverdue" boolean DEFAULT false NOT NULL,
    "NotifiedAboutDeadline" boolean DEFAULT false NOT NULL,
    "ClientConfirmationDeadline" timestamp without time zone
);


ALTER TABLE public."Ticket" OWNER TO postgres;

--
-- Name: TicketAttachment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TicketAttachment" (
    "Id" integer NOT NULL,
    "FileName" character varying(255) NOT NULL,
    "StoredFilePath" character varying(500) NOT NULL,
    "ContentType" character varying(100) NOT NULL,
    "FileSize" bigint NOT NULL,
    "UploadedAt" timestamp without time zone NOT NULL,
    "TicketId" integer NOT NULL,
    "UploadedByUserId" integer NOT NULL
);


ALTER TABLE public."TicketAttachment" OWNER TO postgres;

--
-- Name: TicketAttachment_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TicketAttachment" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TicketAttachment_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: TicketComment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TicketComment" (
    "Id" integer NOT NULL,
    "TicketId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Text" text NOT NULL,
    "IsInternal" boolean DEFAULT true NOT NULL,
    "CreatedAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public."TicketComment" OWNER TO postgres;

--
-- Name: TicketComment_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TicketComment" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TicketComment_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: TicketHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TicketHistory" (
    "Id" integer NOT NULL,
    "TicketId" integer NOT NULL,
    "Action" character varying(100) NOT NULL,
    "Details" text NOT NULL,
    "Timestamp" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public."TicketHistory" OWNER TO postgres;

--
-- Name: TicketHistory_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TicketHistory" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TicketHistory_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Ticket_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Ticket" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Ticket_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: User; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."User" (
    "Id" integer NOT NULL,
    "Username" character varying(50) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" character varying(50) DEFAULT 'Client'::character varying NOT NULL,
    "AvatarPath" character varying(500),
    "Email" character varying(100),
    "CreatedAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "LastLoginAt" timestamp without time zone,
    "IsEmailVerified" boolean NOT NULL,
    "VerificationCode" character varying(10),
    "FailedLoginAttempts" integer DEFAULT 0 NOT NULL,
    "LockedUntil" timestamp without time zone,
    "MustChangePassword" boolean DEFAULT false NOT NULL
);


ALTER TABLE public."User" OWNER TO postgres;

--
-- Name: UserUiSettings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserUiSettings" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "ShowKpiBlock" boolean DEFAULT true NOT NULL,
    "ShowChartsBlock" boolean DEFAULT true NOT NULL,
    "ShowDetailedTable" boolean DEFAULT true NOT NULL,
    "DefaultPeriodDays" integer DEFAULT 30 NOT NULL,
    "RefreshRateSeconds" integer DEFAULT 30 NOT NULL,
    "Theme" character varying(20) DEFAULT 'Light'::character varying NOT NULL
);


ALTER TABLE public."UserUiSettings" OWNER TO postgres;

--
-- Name: UserUiSettings_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."UserUiSettings" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserUiSettings_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: User_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."User" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."User_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: AuditLog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AuditLog" ("Id", "Username", "Action", "Details", "Timestamp") FROM stdin;
1	admin	LoginSuccess	Вход через Debug Mode	2026-05-22 03:11:21.630792
2	admin	Logout	Выход из системы	2026-05-22 03:12:37.392105
3	MAX	Register	Регистрация нового клиента	2026-05-22 03:12:56.752394
4	MAX	LoginSuccess	Роль: Client	2026-05-22 03:13:04.277511
5	MAX	Logout	Выход из системы	2026-05-22 03:13:28.41661
6	admin	LoginSuccess	Вход через Debug Mode	2026-05-22 03:13:38.291075
7	admin	LoginSuccess	Вход через Debug Mode	2026-05-22 03:17:02.102321
8	admin	LoginSuccess	Вход через Debug Mode	2026-06-02 19:17:56.680351
9	admin	LoginSuccess	Вход через Debug Mode	2026-06-02 19:28:18.467872
10	admin	LoginSuccess	Вход через Debug Mode	2026-06-02 19:35:56.750246
11	admin	LoginSuccess	Вход через Debug Mode	2026-06-02 19:41:24.878569
12	admin	LoginSuccess	Вход через Debug Mode	2026-06-02 19:47:32.657971
13	admin	LoginSuccess	Вход через Debug Mode	2026-06-02 19:47:53.088267
14	admin	LoginSuccess	Вход через Debug Mode	2026-06-02 19:49:22.831736
\.


--
-- Data for Name: Client; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Client" ("Id", "Name", "UserId") FROM stdin;
1	Комьюнити Игроков	4
2	Студенты / ВУЗ	5
3	Заказчики (Фриланс)	6
4	MAX	8
\.


--
-- Data for Name: Employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Employee" ("Id", "Name", "Role", "UserId", "MaxActiveTickets") FROM stdin;
1	Lead Dev	Developer	2	20
2	DevOps / Sysadmin	Sysadmin	3	20
3	Главный Администратор	Admin	7	999
\.


--
-- Data for Name: ExternalLink; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ExternalLink" ("Id", "TicketId", "System", "ExternalId", "ExternalKey", "Url", "Direction", "LastSyncedAt", "ContentHash") FROM stdin;
\.


--
-- Data for Name: Feedback; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Feedback" ("Id", "TicketId", "ClientId", "SupportId", "Comment", "Rating", "CreatedAt") FROM stdin;
1	3	1	1	Всё топ, спасибо за помощь!	5	2026-05-22 06:11:05.240955
2	4	3	1	Всё топ, спасибо за помощь!	4	2026-05-22 06:11:05.240955
3	17	2	2	Всё топ, спасибо за помощь!	5	2026-05-22 06:11:05.240955
4	20	2	1	Всё топ, спасибо за помощь!	5	2026-05-22 06:11:05.240955
5	22	3	2	Всё топ, спасибо за помощь!	4	2026-05-22 06:11:05.240955
6	24	3	1	Всё топ, спасибо за помощь!	4	2026-05-22 06:11:05.240955
7	25	3	1	Всё топ, спасибо за помощь!	4	2026-05-22 06:11:05.240955
8	28	3	1	Всё топ, спасибо за помощь!	4	2026-05-22 06:11:05.240955
9	30	3	1	Всё топ, спасибо за помощь!	5	2026-05-22 06:11:05.240955
10	31	3	2	Всё топ, спасибо за помощь!	4	2026-05-22 06:11:05.240955
11	40	3	1	Всё топ, спасибо за помощь!	4	2026-05-22 06:11:05.240955
12	43	3	2	Всё топ, спасибо за помощь!	5	2026-05-22 06:11:05.240955
\.


--
-- Data for Name: IntegrationSettings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."IntegrationSettings" ("Id", "System", "BaseUrl", "ProjectKey", "BoardOrListId", "AuthLogin", "AuthSecret", "DefaultIssueType", "DefaultPriority") FROM stdin;
\.


--
-- Data for Name: KnowledgeArticle; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."KnowledgeArticle" ("Id", "Title", "Content", "AuthorId", "CreatedAt", "UpdatedAt", "ViewCount", "HelpfulCount", "NotHelpfulCount") FROM stdin;
1	Фикс ошибки MaterialDesignThemes: Белый экран при запуске WPF	Проблема: При интеграции MaterialDesignThemes в проект (например, RestoApp) главное окно приложения или окно авторизации открывается полностью белым, а в логах среды выполнения сыплются ошибки сборки (assembly loading exceptions).\n\nРешение:\n1. Убедитесь, что в App.xaml правильно подключены словари ресурсов. Секция <ResourceDictionary.MergedDictionaries> должна содержать корректные пути к стилям BundledTheme и ColorZoneAssist.\n2. Очистите кэш NuGet. Выполните команду: dotnet nuget locals all --clear\n3. Проверьте файлы конфигурации проекта (.csproj). Если версии MaterialDesignThemes и MaterialDesignColors рассинхронизированы, принудительно обновите оба пакета до одной стабильной версии через менеджер пакетов Nuget.\n4. Пересоберите решение (Clean Solution -> Rebuild Solution).	2	2026-05-12 06:16:45.695374	2026-05-22 06:16:45.695374	0	0	0
2	Настройка Nearest-Neighbor фильтрации в Blender для PS1-стиля	При создании лоу-поли моделей (оружие, элементы окружения, фляги) в стиле ретро-игр PS1, стандартное сглаживание текстур портит пиксельную эстетику.\n\nПошаговый гайд для Blender:\n1. Перейдите во вкладку Shading (Редактор шейдеров).\n2. Найдите ноду вашей текстуры (Image Texture).\n3. В выпадающем списке, где по умолчанию стоит "Linear" (Линейная фильтрация), выберите "Closest" (Ближайший сосед / Nearest-Neighbor).\n4. Для экспорта в игровой движок (Godot/Unity): при импорте текстуры в настройках самого движка обязательно отключите Filter (Mipmaps) и переключите режим текстуры на Compress Lossless, а фильтрацию — на Nearest.	1	2026-05-14 06:16:45.695374	2026-05-22 06:16:45.695374	0	0	0
3	Проброс портов для домашнего сервера за NAT (WireGuard + VPS)	Если ваш провайдер выдает серый IP-адрес, запустить домашний сервер (например, для хостинга Telegram-бота на ASP.NET) напрямую из дома не получится, так как порты закрыты изнутри.\n\nРешение через аренду дешевого VPS с белым IP:\n1. Поднимите WireGuard туннель между VPS (сервер) и домашним ПК (клиент).\n2. В конфигурации WireGuard на домашней машине пропишите PersistentKeepalive = 25, чтобы соединение не обрывалось при простое.\n3. На стороне VPS настройте перенаправление трафика (port forwarding) с помощью iptables:\n   sudo iptables -t nat -A PREROUTING -p tcp --dport 8443 -j DNAT --to-destination 10.0.0.2:8443\n4. Теперь все запросы к вебхукам Telegram, приходящие на VPS:8443, будут автоматически улетать на ваш домашний сервер.	3	2026-05-17 06:16:45.695374	2026-05-22 06:16:45.695374	0	0	0
4	Привязка физики к кадрам (FixedUpdate) для мониторов 144Hz+	Проблема: В инди-проектах при тестировании на мониторах с высокой герцовкой (144 Гц, 240 Гц) физика прыжков, перемещения или коллизий может работать некорректно (персонаж прыгает ниже/выше, пролетает сквозь стены), если расчеты завязаны на обычный кадр (Update / _process).\n\nПравило разработки:\n1. Все изменения физических свойств объектов, симуляцию гравитации и вызовы Raycast необходимо обрабатывать исключительно внутри метода FixedUpdate (в Unity) или _physics_process (в Godot).\n2. Перемещение должно умножаться на физический шаг времени (delta), который фиксирован и не зависит от текущего FPS игрока.\n3. Для плавности отображения на мониторах с высокой частотой включайте интерполяцию (Interpolate) в компоненте Rigidbody / CharacterBody.	2	2026-05-18 06:16:45.695374	2026-05-22 06:16:45.695374	0	0	0
5	Решение конфликтов маппинга таблиц в Entity Framework Core	Типичная ошибка при написании курсовых и пет-проектов на C# с использованием EF: "The EntityType ... is not mapped to a table".\n\nЧек-лист для исправления:\n1. Проверьте класс AppDbContext. Каждая сущность, которая должна стать таблицей в базе данных PostgreSQL, должна быть объявлена как публичное свойство public DbSet<T> SubTable { get; set; }.\n2. Если вы используете Fluent API внутри метода OnModelCreating, убедитесь, что конфигурация modelBuilder.Entity<T>() не содержит конфликтующих связей HasOne/WithMany.\n3. Если имена таблиц в PostgreSQL используют верхний регистр или кавычки, явно укажите имя таблицы через атрибут [Table("User")] над классом модели или через .ToTable("User") во Fluent API, иначе EF попытается искать таблицу во множественном числе по умолчанию.	2	2026-05-19 06:16:45.695374	2026-05-22 06:16:45.695374	0	0	0
6	Настройка подключения к Wi-Fi через iwctl в Arch Linux	После чистой установки Arch Linux из консоли управление сетевыми интерфейсами происходит через утилиту iwd.\n\nИнструкция по подключению к сети:\n1. Запустите интерактивную оболочку: iwctl\n2. Выведите список доступных Wi-Fi адаптеров: device list (обычно это wlan0).\n3. Включите сканирование сетей: station wlan0 scan\n4. Отобразите найденные сети: station wlan0 get-networks\n5. Подключитесь к вашей точке доступа: station wlan0 connect "Имя_Сети"\n6. Введите пароль. Выйдите из утилиты через exit. Проверьте пинг: ping -c 3 google.com.	3	2026-05-20 06:16:45.695374	2026-05-22 06:16:45.695374	0	0	0
7	Обход Cloudflare и капчи при парсинге динамических веб-страниц	При написании скриптов для миграции данных (например, парсинг названий треков из HTML веб-плееров музыкальных сервисов) стандартные библиотеки вроде requests или HttpClient могут натыкаться на заглушку Cloudflare.\n\nМетоды обхода:\n1. Вместо сырых HTTP-запросов используйте автоматизацию браузера через Selenium или Playwright с флагом headless = false, чтобы имитировать поведение реального пользователя.\n2. Используйте библиотеку undetected-chromedriver для Python, которая модифицирует переменные окружения ChromeDriver, скрывая автоматизацию от защитных систем.\n3. Обязательно подставляйте валидный User-Agent текущего поколения браузеров и делайте случайные задержки (time.sleep) между кликами по элементам DOM-дерева.	1	2026-05-21 06:16:45.695374	2026-05-22 06:16:45.695374	0	0	0
\.


--
-- Data for Name: MlModelMetrics; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."MlModelMetrics" ("Id", "ModelType", "TrainedAt", "MicroAccuracy", "MacroAccuracy", "LogLoss", "SampleCount") FROM stdin;
1	Category	2026-06-02 19:35:53.769029	0.5454545454545454	0.325	1.5097119019882337	50
2	Priority	2026-06-02 19:35:55.01722	0.6363636363636364	0.6	1.014435622260554	50
3	Category	2026-06-02 19:41:28.153643	0.5454545454545454	0.325	1.5076283880647936	50
4	Priority	2026-06-02 19:41:31.638616	0.6363636363636364	0.6	1.0145469632450999	50
5	Category	2026-06-02 19:47:28.952226	0.5454545454545454	0.325	1.5101954762723409	50
6	Priority	2026-06-02 19:47:30.042204	0.6363636363636364	0.6	1.0144799239150977	50
7	Category	2026-06-02 19:47:58.13387	0.5454545454545454	0.325	1.5101841700846146	50
8	Priority	2026-06-02 19:48:00.440697	0.6363636363636364	0.6	1.0148104941920861	50
9	Category	2026-06-02 19:49:27.953664	0.5454545454545454	0.325	1.5104665936473738	50
10	Priority	2026-06-02 19:49:30.309741	0.6363636363636364	0.6	1.0144438785996694	50
11	Category	2026-06-04 21:11:47.235278	0.5454545454545454	0.325	1.5093640233370451	50
12	Priority	2026-06-04 21:11:48.420796	0.6363636363636364	0.6	1.0144616778405409	50
\.


--
-- Data for Name: Notification; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Notification" ("Id", "UserId", "Title", "Message", "Type", "TicketId", "CreatedAt", "IsRead") FROM stdin;
\.


--
-- Data for Name: NotificationSettings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."NotificationSettings" ("Id", "UserId", "NotifyOnNewTickets", "NotifyOnStatusChanged", "NotifyOnComments", "NotifyOnDueSoon", "DueSoonThresholdMinutes", "PlaySound", "ShowToast", "EmailEnabled") FROM stdin;
1	1	t	t	t	t	120	t	t	f
2	2	t	t	t	t	120	t	t	f
3	3	t	t	t	t	120	t	t	f
4	4	t	t	t	t	120	t	t	f
5	5	t	t	t	t	120	t	t	f
6	6	t	t	t	t	120	t	t	f
7	7	t	t	t	t	60	t	t	f
\.


--
-- Data for Name: PasswordResetToken; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."PasswordResetToken" ("Id", "UserId", "Token", "ExpiresAt", "IsUsed", "CreatedAt") FROM stdin;
\.


--
-- Data for Name: SearchPreset; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."SearchPreset" ("Id", "UserId", "Name", "TextQuery", "Status", "Category", "Priority", "CreatedFrom", "CreatedTo") FROM stdin;
\.


--
-- Data for Name: Solution; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Solution" ("Id", "ResolutionText", "ResolutionDate", "KnowledgeArticleId", "TicketId") FROM stdin;
1	Сделали патч/фикс. Проблема устранена.	2026-05-22 06:11:05.240955	\N	3
2	Сделали патч/фикс. Проблема устранена.	2026-05-22 06:11:05.240955	\N	4
3	Сделали патч/фикс. Проблема устранена.	2026-05-22 06:11:05.240955	\N	17
4	Сделали патч/фикс. Проблема устранена.	2026-05-22 06:11:05.240955	\N	20
5	Сделали патч/фикс. Проблема устранена.	2026-05-22 06:11:05.240955	\N	22
6	Сделали патч/фикс. Проблема устранена.	2026-05-22 06:11:05.240955	\N	24
7	Сделали патч/фикс. Проблема устранена.	2026-05-22 06:11:05.240955	\N	25
8	Сделали патч/фикс. Проблема устранена.	2026-05-22 06:11:05.240955	\N	28
9	Сделали патч/фикс. Проблема устранена.	2026-05-22 06:11:05.240955	\N	30
10	Сделали патч/фикс. Проблема устранена.	2026-05-22 06:11:05.240955	\N	31
11	Сделали патч/фикс. Проблема устранена.	2026-05-22 06:11:05.240955	\N	40
12	Сделали патч/фикс. Проблема устранена.	2026-05-22 06:11:05.240955	\N	43
\.


--
-- Data for Name: Ticket; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Ticket" ("Id", "Title", "Description", "Status", "Priority", "Category", "CreatedAt", "DueAt", "ClosedAt", "AttachmentPath", "AttachmentFileName", "AttachmentContentType", "AttachmentSize", "AssigneeEmployeeId", "ClientId", "IsOverdue", "NotifiedAboutDeadline", "ClientConfirmationDeadline") FROM stdin;
1	Проваливаюсь под текстуры в хабе	После патча 0.4.2 в стартовой локации, если прыгнуть возле мусорки в углу, персонаж летит в бездну. Коллизии слетели.	Resolved	2	1	2026-04-09 12:59:39.820415	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
2	Сломался шейдер VHS глитча	На новых драйверах Nvidia шейдер постпроцесса (постпанк глитч) выдает просто черный экран. В логах ругается на HLSL компиляцию.	Resolved	3	4	2026-05-18 03:57:47.750737	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
3	Враги не реагируют на выстрелы	AI скрипт в Godot выдает null reference при попытке получить компонент Health. Боты просто стоят и смотрят.	Closed	3	1	2026-04-13 16:52:26.745122	\N	\N	\N	\N	\N	\N	1	1	f	f	\N
4	Утечка памяти при спавне партиклов	Если долго стрелять из АК-47, потребление RAM улетает за 8 гигов и игра крашится. Видимо, Garbage Collector не успевает.	Closed	3	1	2026-04-05 11:41:40.336488	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
5	Nearest-neighbor интерполяция мылит	В Blender текстура выглядит как тру-PS1 (пиксельно), а при импорте в движок она сглаживается. Где отключить мипмапы?	In Progress	2	4	2026-04-20 07:48:52.452557	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
6	Проблема с навигационной сеткой (NavMesh)	Босс застревает в дверном проеме. Кажется, радиус агента в навмеше больше, чем ширина прохода.	Resolved	2	1	2026-04-02 09:06:18.584467	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
7	Рассинхрон звука перезарядки	Анимация заканчивается, а звук лязга затвора проигрывается еще секунду. Нужно поправить тайминги в AnimationPlayer.	In Progress	3	4	2026-04-02 14:34:30.390421	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
8	Не работает сборка под Linux	При экспорте игры под Linux выдает ошибку линковки. Библиотека Steamworks.NET не подтягивает .so файл.	Resolved	1	2	2026-05-13 20:02:45.081317	\N	\N	\N	\N	\N	\N	2	3	f	f	\N
9	Бьются сохранения после альт-таба	Если свернуть игру во время автосейва, JSON файл перезаписывается пустым массивом. Нужна защита от прерывания.	In Progress	2	1	2026-04-20 19:22:16.111163	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
10	Ужасные тени от Point Light	В закрытых помещениях тени рябят (shadow acne). Пробовал крутить bias, но тогда появляется отрыв теней (peter-panning).	In Progress	3	4	2026-05-18 07:27:42.712715	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
11	Интеграция с Discord Rich Presence	Нужно добавить, чтобы в Дискорде показывалось, в какой локации находится игрок и сколько у него хп. Библиотеку уже скачал.	Open	1	1	2026-04-28 08:41:07.814889	\N	\N	\N	\N	\N	\N	\N	3	f	f	\N
12	Глитч физики при 144Hz	У кого мониторы 144 герца, физика прыжка работает иначе (персонаж прыгает ниже). Нужно привязать физику к FixedUpdate.	Resolved	1	1	2026-03-31 17:43:38.074922	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
13	Перенос UI на новый холст	Инвентарь съезжает при разрешении 21:9. Нужно перенастроить анкоры (Anchors) на растяжение по углам.	Resolved	2	3	2026-04-24 05:19:57.35135	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
14	Странный баг с рейкастом	Raycast оружия не пробивает стеклянные поверхности, хотя они настроены на слой TransparentFX. Пуля просто исчезает.	Resolved	3	1	2026-05-08 00:19:59.064619	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
15	Лоу-поли фляга выглядит странно	Нормали вывернуты наизнанку на крышке фляги. Из-за этого освещение работает задом наперед. Нужно сделать Recalculate Normals в блендере.	Resolved	1	4	2026-04-15 12:25:23.224249	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
16	Курсач: ошибка в Entity Framework	Пытаюсь сделать миграцию для Service Desk, вываливается "The EntityType is not mapped to a table". Где-то забыл DbSet прописать.	Resolved	3	1	2026-03-31 04:41:12.323047	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
17	Не пускает в университетский VPN	Срок действия сертификата OpenVPN для доступа к библиотеке МИСиС истек вчера. Как сгенерировать новый?	Closed	3	2	2026-03-26 17:37:59.561196	\N	\N	\N	\N	\N	\N	2	2	f	f	\N
18	Форматирование пояснительной записки	По ГОСТу нужно сделать рамки на всех страницах в Ворде и чтобы номер страницы был внутри рамки. У меня всё плывет.	In Progress	2	5	2026-03-28 21:35:59.729291	\N	\N	\N	\N	\N	\N	2	3	f	f	\N
19	Скрипт парсинга расписания отвалился	Универ обновил дизайн сайта расписания. Мой Python-парсер (BeautifulSoup) больше не находит теги <table>. Надо переписать под новый API.	In Progress	1	1	2026-03-27 20:31:16.058031	\N	\N	\N	\N	\N	\N	1	2	f	f	\N
20	Ошибка установки ML.NET	В проекте КР_Ханников при попытке добавить пакет Microsoft.ML в NuGet пишет, что он несовместим с текущей версией .NET Core.	Closed	2	1	2026-04-12 11:55:28.621045	\N	\N	\N	\N	\N	\N	1	2	f	f	\N
21	Доступ к удаленному серверу	Нам на кафедру выдали доступ к виртуалке на Ubuntu. Я случайно заблокировал свой IP через fail2ban, когда вводил пароль.	Resolved	3	2	2026-03-29 07:51:14.644555	\N	\N	\N	\N	\N	\N	2	3	f	f	\N
22	Проблема с PostgreSQL локально	Случайно удалил дефолтного юзера postgres. Теперь pgAdmin вообще не коннектится к локальной базе. Как восстановить?	Closed	2	2	2026-04-18 01:53:31.802287	\N	\N	\N	\N	\N	\N	2	3	f	f	\N
23	Ошибка в WPF биндингах	В модуле Календарь не обновляется список событий при добавлении нового в базу. INotifyPropertyChanged реализован. Помогите найти баг.	Resolved	2	1	2026-04-25 03:24:48.562572	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
24	Лаба по C++ выдает Segmentation fault	При попытке обратиться к элементу массива по указателю программа крашится. Кажется, выхожу за пределы памяти.	Closed	2	1	2026-04-05 11:35:59.944459	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
25	Зависает Jupyter Notebook	Когда запускаю обучение нейронки (SdcaMaximumEntropy) на 50к записей, вкладка в браузере просто умирает. Нужно запускать локально?	Closed	2	1	2026-04-27 20:54:43.320305	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
26	Бот упал после переноса на домашний сервер	Перенес бота с VPS на домашний комп. Вебхуки телеграма перестали приходить, видимо провайдер блочит 8443 порт.	Open	2	2	2026-04-09 10:33:25.967741	\N	\N	\N	\N	\N	\N	\N	3	f	f	\N
27	Заказчик просит убрать кнопку	По ТЗ модуль расписания должен быть автоматическим. Клиент просит выпилить кнопку "Создать" из интерфейса.	In Progress	1	3	2026-04-12 01:32:31.721316	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
28	WordPress выдает белый экран (WSOD)	После обновления плагина Elementor сайт лег. В логах php-fpm ошибка Fatal error: Allowed memory size exhausted.	Closed	2	1	2026-05-01 17:37:23.73748	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
29	SSL сертификат Let's Encrypt не обновился	Крон отработал, но certbot выдал ошибку валидации DNS. Доступ к сайту теперь горит красным (NET::ERR_CERT_DATE_INVALID).	Resolved	3	2	2026-04-28 22:56:11.388806	\N	\N	\N	\N	\N	\N	2	3	f	f	\N
30	Спарсить Яндекс Музыку для Spotify	Нужен скрипт, который пройдется по HTML коду Я.Музыки, выдернет названия 569 треков и сохранит их в CSV файл для миграции.	Closed	1	1	2026-05-04 09:17:44.698187	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
31	Docker контейнер уходит в CrashLoopBackOff	Настроил docker-compose для Postgres и Node.js. Нода падает сразу при старте, потому что база еще не успела инициализироваться.	Closed	2	2	2026-04-01 14:37:46.365655	\N	\N	\N	\N	\N	\N	2	3	f	f	\N
32	Кривая верстка на мобилках	Сайт-визитка отлично выглядит на ПК, но на айфонах сетка (CSS Grid) схлопывается в одну колонку без отступов. Нужно дописать media queries.	Open	2	3	2026-04-11 11:59:43.603852	\N	\N	\N	\N	\N	\N	\N	3	f	f	\N
33	RestoApp: Ошибка MaterialDesignThemes	Пытаюсь запустить проект ресторана. Сыплет assembly loading issues для библиотек MaterialDesign. Окно просто белое.	Open	1	1	2026-04-15 14:58:35.19465	\N	\N	\N	\N	\N	\N	\N	3	f	f	\N
34	Парсер ломается об капчу	Скрипт на Selenium собирал данные конкурентов, но сегодня Cloudflare включил капчу. Нужно прикрутить анти-капча сервис.	Resolved	3	1	2026-04-01 21:43:34.78847	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
35	Миграция с SQLite на PostgreSQL	Нужно перенести данные из файла .db в нормальную базу. Пытался через pgloader, но ругается на форматы дат.	In Progress	2	2	2026-05-06 05:20:21.747746	\N	\N	\N	\N	\N	\N	2	3	f	f	\N
36	Telegram бот шлет дубли сообщений	Если юзер нажимает inline-кнопку дважды, бот начинает обрабатывать оба коллбека. Нужно добавить проверку на состояние.	Resolved	1	1	2026-05-07 21:08:59.742029	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
37	Не работает отправка писем через SMTP	Настроил MailKit в C#, но Gmail блочит авторизацию, пишет "Less secure apps turned off". Как настроить через App Passwords?	In Progress	3	2	2026-04-18 11:37:02.185664	\N	\N	\N	\N	\N	\N	2	3	f	f	\N
38	Слетают шрифты в Figma	Открываю макет от другого дизайнера, а вместо красивого гротеска стоят дефолтные засечки. Пишет Missing Fonts.	Resolved	2	3	2026-04-07 19:58:31.095362	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
39	Пагинация грузит всю базу	В админке загружаются все 100 тысяч записей сразу, а потом режутся на фронте. Страница грузится 40 секунд. Нужен OFFSET/FETCH.	In Progress	1	1	2026-05-12 07:57:14.497927	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
40	CORS ошибка при запросе к API	Фронт на React не может получить данные с бекенда на ASP.NET. В консоли пишет "No Access-Control-Allow-Origin header is present".	Closed	3	1	2026-04-13 04:10:13.817555	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
41	Arch Linux не видит Wi-Fi	Поставил чистый Арч, установил nucleus-shell. Пытаюсь подключиться через iwctl, но wlan0 вообще нет в списке устройств.	In Progress	3	2	2026-04-14 17:08:59.883332	\N	\N	\N	\N	\N	\N	2	3	f	f	\N
42	Малинка уходит в троттлинг	Raspberry Pi 4 греется до 85 градусов при компиляции ядра. Поставил кулер, но он не крутится. Как настроить ШИМ в конфиге?	Open	1	5	2026-05-15 02:59:17.969579	\N	\N	\N	\N	\N	\N	\N	3	f	f	\N
43	Home Assistant потерял Zigbee стик	После перезагрузки сервера HA не видит адаптер Sonoff. В dmesg пишет, что ttyUSB0 отвалился.	Closed	2	2	2026-03-29 22:58:51.429234	\N	\N	\N	\N	\N	\N	2	3	f	f	\N
44	Ошибка GRUB после обновления ядра	Обновил систему (pacman -Syu), перезагружаюсь — выкидывает в grub rescue. Кажется, слетел initramfs.	Resolved	3	2	2026-05-12 23:28:22.388121	\N	\N	\N	\N	\N	\N	2	3	f	f	\N
45	Трещит звук в JACK Audio	Пытаюсь настроить аудиоинтерфейс для записи гитары. Если ставлю буфер 128 сэмплов — идут XRUN (щелчки).	Open	1	5	2026-05-11 19:03:05.814519	\N	\N	\N	\N	\N	\N	\N	3	f	f	\N
46	Проброс портов за NAT	Провайдер выдал серый IP. Не могу подключиться к своему домашнему серверу снаружи. Подскажите, как поднять WireGuard туннель через VPS?	Resolved	3	2	2026-04-22 11:57:05.591315	\N	\N	\N	\N	\N	\N	2	3	f	f	\N
47	Proxmox не запускает виртуалку	Создал VM для Windows 10, нажимаю Start — ругается на IOMMU. В биосе виртуализация включена, куда копать?	Open	2	2	2026-04-27 12:06:40.738079	\N	\N	\N	\N	\N	\N	\N	3	f	f	\N
48	Настройка Samba шары в домашней сети	Сделал папку на линуксе, с Винды ее видно, но при попытке зайти просит пароль, хотя я настроил guest ok = yes.	Open	1	2	2026-05-09 18:56:30.650865	\N	\N	\N	\N	\N	\N	\N	3	f	f	\N
49	OBS дропает кадры (NVENC)	Во время стрима инди-игры кодировщик перегружается. Битрейт 6000, видюха вроде тянет, но фризы дикие. Стоит ли перейти на x264?	Resolved	1	4	2026-04-02 12:22:51.707904	\N	\N	\N	\N	\N	\N	1	3	f	f	\N
50	Щелкает жесткий диск в NAS	Сетевое хранилище стало издавать странные звуки. В SMART показателях Reallocated Sector Count начал расти. Спасать данные?	Open	1	5	2026-04-24 06:04:00.604991	\N	\N	\N	\N	\N	\N	\N	3	f	f	\N
\.


--
-- Data for Name: TicketAttachment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."TicketAttachment" ("Id", "FileName", "StoredFilePath", "ContentType", "FileSize", "UploadedAt", "TicketId", "UploadedByUserId") FROM stdin;
\.


--
-- Data for Name: TicketComment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."TicketComment" ("Id", "TicketId", "UserId", "Text", "IsInternal", "CreatedAt") FROM stdin;
1	1	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
2	1	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
3	2	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
4	2	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
5	3	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
6	3	4	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
7	4	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
8	4	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
9	5	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
10	5	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
11	6	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
12	6	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
13	7	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
14	7	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
15	8	3	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
16	8	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
17	9	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
18	9	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
19	10	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
20	10	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
21	12	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
22	12	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
23	13	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
24	13	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
25	14	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
26	14	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
27	15	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
28	15	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
29	16	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
30	16	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
31	17	3	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
32	17	5	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
33	18	3	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
34	18	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
35	19	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
36	19	5	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
37	20	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
38	20	5	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
39	21	3	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
40	21	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
41	22	3	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
42	22	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
43	23	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
44	23	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
45	24	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
46	24	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
47	25	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
48	25	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
49	27	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
50	27	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
51	28	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
52	28	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
53	29	3	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
54	29	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
55	30	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
56	30	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
57	31	3	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
58	31	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
59	34	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
60	34	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
61	35	3	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
62	35	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
63	36	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
64	36	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
65	37	3	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
66	37	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
67	38	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
68	38	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
69	39	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
70	39	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
71	40	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
72	40	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
73	41	3	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
74	41	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
75	43	3	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
76	43	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
77	44	3	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
78	44	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
79	46	3	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
80	46	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
81	49	2	Принял тикет. Пришли, пожалуйста, полные логи ошибки.	f	2026-04-07 06:11:05.240955
82	49	6	Залил логи на Pastebin, посмотри.	f	2026-04-08 06:11:05.240955
\.


--
-- Data for Name: TicketHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."TicketHistory" ("Id", "TicketId", "Action", "Details", "Timestamp") FROM stdin;
1	1	Created	Заявка открыта	2026-03-23 06:11:05.240955
2	1	Assigned	Взято в работу	2026-04-02 06:11:05.240955
3	2	Created	Заявка открыта	2026-03-23 06:11:05.240955
4	2	Assigned	Взято в работу	2026-04-02 06:11:05.240955
5	3	Created	Заявка открыта	2026-03-23 06:11:05.240955
6	3	Assigned	Взято в работу	2026-04-02 06:11:05.240955
7	4	Created	Заявка открыта	2026-03-23 06:11:05.240955
8	4	Assigned	Взято в работу	2026-04-02 06:11:05.240955
9	5	Created	Заявка открыта	2026-03-23 06:11:05.240955
10	5	Assigned	Взято в работу	2026-04-02 06:11:05.240955
11	6	Created	Заявка открыта	2026-03-23 06:11:05.240955
12	6	Assigned	Взято в работу	2026-04-02 06:11:05.240955
13	7	Created	Заявка открыта	2026-03-23 06:11:05.240955
14	7	Assigned	Взято в работу	2026-04-02 06:11:05.240955
15	8	Created	Заявка открыта	2026-03-23 06:11:05.240955
16	8	Assigned	Взято в работу	2026-04-02 06:11:05.240955
17	9	Created	Заявка открыта	2026-03-23 06:11:05.240955
18	9	Assigned	Взято в работу	2026-04-02 06:11:05.240955
19	10	Created	Заявка открыта	2026-03-23 06:11:05.240955
20	10	Assigned	Взято в работу	2026-04-02 06:11:05.240955
21	11	Created	Заявка открыта	2026-03-23 06:11:05.240955
22	12	Created	Заявка открыта	2026-03-23 06:11:05.240955
23	12	Assigned	Взято в работу	2026-04-02 06:11:05.240955
24	13	Created	Заявка открыта	2026-03-23 06:11:05.240955
25	13	Assigned	Взято в работу	2026-04-02 06:11:05.240955
26	14	Created	Заявка открыта	2026-03-23 06:11:05.240955
27	14	Assigned	Взято в работу	2026-04-02 06:11:05.240955
28	15	Created	Заявка открыта	2026-03-23 06:11:05.240955
29	15	Assigned	Взято в работу	2026-04-02 06:11:05.240955
30	16	Created	Заявка открыта	2026-03-23 06:11:05.240955
31	16	Assigned	Взято в работу	2026-04-02 06:11:05.240955
32	17	Created	Заявка открыта	2026-03-23 06:11:05.240955
33	17	Assigned	Взято в работу	2026-04-02 06:11:05.240955
34	18	Created	Заявка открыта	2026-03-23 06:11:05.240955
35	18	Assigned	Взято в работу	2026-04-02 06:11:05.240955
36	19	Created	Заявка открыта	2026-03-23 06:11:05.240955
37	19	Assigned	Взято в работу	2026-04-02 06:11:05.240955
38	20	Created	Заявка открыта	2026-03-23 06:11:05.240955
39	20	Assigned	Взято в работу	2026-04-02 06:11:05.240955
40	21	Created	Заявка открыта	2026-03-23 06:11:05.240955
41	21	Assigned	Взято в работу	2026-04-02 06:11:05.240955
42	22	Created	Заявка открыта	2026-03-23 06:11:05.240955
43	22	Assigned	Взято в работу	2026-04-02 06:11:05.240955
44	23	Created	Заявка открыта	2026-03-23 06:11:05.240955
45	23	Assigned	Взято в работу	2026-04-02 06:11:05.240955
46	24	Created	Заявка открыта	2026-03-23 06:11:05.240955
47	24	Assigned	Взято в работу	2026-04-02 06:11:05.240955
48	25	Created	Заявка открыта	2026-03-23 06:11:05.240955
49	25	Assigned	Взято в работу	2026-04-02 06:11:05.240955
50	26	Created	Заявка открыта	2026-03-23 06:11:05.240955
51	27	Created	Заявка открыта	2026-03-23 06:11:05.240955
52	27	Assigned	Взято в работу	2026-04-02 06:11:05.240955
53	28	Created	Заявка открыта	2026-03-23 06:11:05.240955
54	28	Assigned	Взято в работу	2026-04-02 06:11:05.240955
55	29	Created	Заявка открыта	2026-03-23 06:11:05.240955
56	29	Assigned	Взято в работу	2026-04-02 06:11:05.240955
57	30	Created	Заявка открыта	2026-03-23 06:11:05.240955
58	30	Assigned	Взято в работу	2026-04-02 06:11:05.240955
59	31	Created	Заявка открыта	2026-03-23 06:11:05.240955
60	31	Assigned	Взято в работу	2026-04-02 06:11:05.240955
61	32	Created	Заявка открыта	2026-03-23 06:11:05.240955
62	33	Created	Заявка открыта	2026-03-23 06:11:05.240955
63	34	Created	Заявка открыта	2026-03-23 06:11:05.240955
64	34	Assigned	Взято в работу	2026-04-02 06:11:05.240955
65	35	Created	Заявка открыта	2026-03-23 06:11:05.240955
66	35	Assigned	Взято в работу	2026-04-02 06:11:05.240955
67	36	Created	Заявка открыта	2026-03-23 06:11:05.240955
68	36	Assigned	Взято в работу	2026-04-02 06:11:05.240955
69	37	Created	Заявка открыта	2026-03-23 06:11:05.240955
70	37	Assigned	Взято в работу	2026-04-02 06:11:05.240955
71	38	Created	Заявка открыта	2026-03-23 06:11:05.240955
72	38	Assigned	Взято в работу	2026-04-02 06:11:05.240955
73	39	Created	Заявка открыта	2026-03-23 06:11:05.240955
74	39	Assigned	Взято в работу	2026-04-02 06:11:05.240955
75	40	Created	Заявка открыта	2026-03-23 06:11:05.240955
76	40	Assigned	Взято в работу	2026-04-02 06:11:05.240955
77	41	Created	Заявка открыта	2026-03-23 06:11:05.240955
78	41	Assigned	Взято в работу	2026-04-02 06:11:05.240955
79	42	Created	Заявка открыта	2026-03-23 06:11:05.240955
80	43	Created	Заявка открыта	2026-03-23 06:11:05.240955
81	43	Assigned	Взято в работу	2026-04-02 06:11:05.240955
82	44	Created	Заявка открыта	2026-03-23 06:11:05.240955
83	44	Assigned	Взято в работу	2026-04-02 06:11:05.240955
84	45	Created	Заявка открыта	2026-03-23 06:11:05.240955
85	46	Created	Заявка открыта	2026-03-23 06:11:05.240955
86	46	Assigned	Взято в работу	2026-04-02 06:11:05.240955
87	47	Created	Заявка открыта	2026-03-23 06:11:05.240955
88	48	Created	Заявка открыта	2026-03-23 06:11:05.240955
89	49	Created	Заявка открыта	2026-03-23 06:11:05.240955
90	49	Assigned	Взято в работу	2026-04-02 06:11:05.240955
91	50	Created	Заявка открыта	2026-03-23 06:11:05.240955
\.


--
-- Data for Name: User; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."User" ("Id", "Username", "PasswordHash", "Role", "AvatarPath", "Email", "CreatedAt", "LastLoginAt", "IsEmailVerified", "VerificationCode", "FailedLoginAttempts", "LockedUntil", "MustChangePassword") FROM stdin;
1	max_creator	hash1	Admin	\N	max@fba.dev	2026-05-22 06:11:05.240955	\N	t	\N	0	\N	f
2	csharp_guru	hash2	Employee	\N	dev@indie.team	2026-05-22 06:11:05.240955	\N	t	\N	0	\N	f
3	linux_void	hash3	Employee	\N	sys@homelab.net	2026-05-22 06:11:05.240955	\N	t	\N	0	\N	f
4	player_one	hash4	Client	\N	player@discord.gg	2026-05-22 06:11:05.240955	\N	t	\N	0	\N	f
5	misis_student	hash5	Client	\N	student@misis.ru	2026-05-22 06:11:05.240955	\N	t	\N	0	\N	f
6	freelance_ninja	hash6	Client	\N	order@kwork.ru	2026-05-22 06:11:05.240955	\N	t	\N	0	\N	f
7	admin	$2a$13$2uAMJPfsIx6AFu8TDbsM/OwkdFIBuxZu/Gs/KkRhvrJdLviPdy4J6	Admin	\N	\N	2026-05-22 03:11:13.118804	\N	t	\N	0	\N	f
8	MAX	$2a$13$3wuFgUQ0d52QuKjWJvBoZOGrs4EsOmprh6FbL85A1S9xHiAVdwp5e	Client	\N		2026-05-22 03:12:56.705698	\N	t	\N	0	\N	f
\.


--
-- Data for Name: UserUiSettings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."UserUiSettings" ("Id", "UserId", "ShowKpiBlock", "ShowChartsBlock", "ShowDetailedTable", "DefaultPeriodDays", "RefreshRateSeconds", "Theme") FROM stdin;
1	1	t	t	t	30	60	Dark
2	2	t	t	t	30	60	Dark
3	3	t	t	t	30	60	Dark
4	4	t	t	t	30	60	Dark
5	5	t	t	t	30	60	Dark
6	6	t	t	t	30	60	Dark
7	7	t	t	t	30	30	Light
\.


--
-- Name: AuditLog_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AuditLog_Id_seq"', 14, true);


--
-- Name: Client_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Client_Id_seq"', 4, true);


--
-- Name: Employee_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Employee_Id_seq"', 3, true);


--
-- Name: ExternalLink_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ExternalLink_Id_seq"', 1, false);


--
-- Name: Feedback_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Feedback_Id_seq"', 12, true);


--
-- Name: IntegrationSettings_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."IntegrationSettings_Id_seq"', 1, false);


--
-- Name: KnowledgeArticle_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."KnowledgeArticle_Id_seq"', 7, true);


--
-- Name: MlModelMetrics_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."MlModelMetrics_Id_seq"', 12, true);


--
-- Name: NotificationSettings_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."NotificationSettings_Id_seq"', 7, true);


--
-- Name: Notification_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Notification_Id_seq"', 1, false);


--
-- Name: PasswordResetToken_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."PasswordResetToken_Id_seq"', 1, false);


--
-- Name: SearchPreset_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SearchPreset_Id_seq"', 1, false);


--
-- Name: Solution_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Solution_Id_seq"', 12, true);


--
-- Name: TicketAttachment_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."TicketAttachment_Id_seq"', 1, false);


--
-- Name: TicketComment_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."TicketComment_Id_seq"', 82, true);


--
-- Name: TicketHistory_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."TicketHistory_Id_seq"', 91, true);


--
-- Name: Ticket_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Ticket_Id_seq"', 50, true);


--
-- Name: UserUiSettings_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."UserUiSettings_Id_seq"', 7, true);


--
-- Name: User_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."User_Id_seq"', 8, true);


--
-- Name: AuditLog PK_AuditLog; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AuditLog"
    ADD CONSTRAINT "PK_AuditLog" PRIMARY KEY ("Id");


--
-- Name: Client PK_Client; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Client"
    ADD CONSTRAINT "PK_Client" PRIMARY KEY ("Id");


--
-- Name: Employee PK_Employee; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Employee"
    ADD CONSTRAINT "PK_Employee" PRIMARY KEY ("Id");


--
-- Name: ExternalLink PK_ExternalLink; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ExternalLink"
    ADD CONSTRAINT "PK_ExternalLink" PRIMARY KEY ("Id");


--
-- Name: Feedback PK_Feedback; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Feedback"
    ADD CONSTRAINT "PK_Feedback" PRIMARY KEY ("Id");


--
-- Name: IntegrationSettings PK_IntegrationSettings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."IntegrationSettings"
    ADD CONSTRAINT "PK_IntegrationSettings" PRIMARY KEY ("Id");


--
-- Name: KnowledgeArticle PK_KnowledgeArticle; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."KnowledgeArticle"
    ADD CONSTRAINT "PK_KnowledgeArticle" PRIMARY KEY ("Id");


--
-- Name: MlModelMetrics PK_MlModelMetrics; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MlModelMetrics"
    ADD CONSTRAINT "PK_MlModelMetrics" PRIMARY KEY ("Id");


--
-- Name: Notification PK_Notification; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Notification"
    ADD CONSTRAINT "PK_Notification" PRIMARY KEY ("Id");


--
-- Name: NotificationSettings PK_NotificationSettings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."NotificationSettings"
    ADD CONSTRAINT "PK_NotificationSettings" PRIMARY KEY ("Id");


--
-- Name: PasswordResetToken PK_PasswordResetToken; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PasswordResetToken"
    ADD CONSTRAINT "PK_PasswordResetToken" PRIMARY KEY ("Id");


--
-- Name: SearchPreset PK_SearchPreset; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SearchPreset"
    ADD CONSTRAINT "PK_SearchPreset" PRIMARY KEY ("Id");


--
-- Name: Solution PK_Solution; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Solution"
    ADD CONSTRAINT "PK_Solution" PRIMARY KEY ("Id");


--
-- Name: Ticket PK_Ticket; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Ticket"
    ADD CONSTRAINT "PK_Ticket" PRIMARY KEY ("Id");


--
-- Name: TicketAttachment PK_TicketAttachment; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TicketAttachment"
    ADD CONSTRAINT "PK_TicketAttachment" PRIMARY KEY ("Id");


--
-- Name: TicketComment PK_TicketComment; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TicketComment"
    ADD CONSTRAINT "PK_TicketComment" PRIMARY KEY ("Id");


--
-- Name: TicketHistory PK_TicketHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TicketHistory"
    ADD CONSTRAINT "PK_TicketHistory" PRIMARY KEY ("Id");


--
-- Name: User PK_User; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "PK_User" PRIMARY KEY ("Id");


--
-- Name: UserUiSettings PK_UserUiSettings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserUiSettings"
    ADD CONSTRAINT "PK_UserUiSettings" PRIMARY KEY ("Id");


--
-- Name: IX_Client_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Client_UserId" ON public."Client" USING btree ("UserId");


--
-- Name: IX_Employee_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Employee_UserId" ON public."Employee" USING btree ("UserId");


--
-- Name: IX_ExternalLink_TicketId_System; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_ExternalLink_TicketId_System" ON public."ExternalLink" USING btree ("TicketId", "System");


--
-- Name: IX_Feedback_ClientId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Feedback_ClientId" ON public."Feedback" USING btree ("ClientId");


--
-- Name: IX_Feedback_SupportId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Feedback_SupportId" ON public."Feedback" USING btree ("SupportId");


--
-- Name: IX_Feedback_TicketId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Feedback_TicketId" ON public."Feedback" USING btree ("TicketId");


--
-- Name: IX_IntegrationSettings_System; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_IntegrationSettings_System" ON public."IntegrationSettings" USING btree ("System");


--
-- Name: IX_NotificationSettings_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_NotificationSettings_UserId" ON public."NotificationSettings" USING btree ("UserId");


--
-- Name: IX_Notification_TicketId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Notification_TicketId" ON public."Notification" USING btree ("TicketId");


--
-- Name: IX_Notification_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Notification_UserId" ON public."Notification" USING btree ("UserId");


--
-- Name: IX_PasswordResetToken_Token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_PasswordResetToken_Token" ON public."PasswordResetToken" USING btree ("Token");


--
-- Name: IX_PasswordResetToken_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PasswordResetToken_UserId" ON public."PasswordResetToken" USING btree ("UserId");


--
-- Name: IX_SearchPreset_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_SearchPreset_UserId" ON public."SearchPreset" USING btree ("UserId");


--
-- Name: IX_Solution_TicketId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Solution_TicketId" ON public."Solution" USING btree ("TicketId");


--
-- Name: IX_TicketAttachment_TicketId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_TicketAttachment_TicketId" ON public."TicketAttachment" USING btree ("TicketId");


--
-- Name: IX_TicketAttachment_UploadedByUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_TicketAttachment_UploadedByUserId" ON public."TicketAttachment" USING btree ("UploadedByUserId");


--
-- Name: IX_TicketComment_TicketId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_TicketComment_TicketId" ON public."TicketComment" USING btree ("TicketId");


--
-- Name: IX_TicketComment_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_TicketComment_UserId" ON public."TicketComment" USING btree ("UserId");


--
-- Name: IX_TicketHistory_TicketId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_TicketHistory_TicketId" ON public."TicketHistory" USING btree ("TicketId");


--
-- Name: IX_Ticket_AssigneeEmployeeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Ticket_AssigneeEmployeeId" ON public."Ticket" USING btree ("AssigneeEmployeeId");


--
-- Name: IX_Ticket_ClientId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Ticket_ClientId" ON public."Ticket" USING btree ("ClientId");


--
-- Name: IX_UserUiSettings_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_UserUiSettings_UserId" ON public."UserUiSettings" USING btree ("UserId");


--
-- Name: IX_User_Username; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_User_Username" ON public."User" USING btree ("Username");


--
-- Name: Client FK_Client_User_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Client"
    ADD CONSTRAINT "FK_Client_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE CASCADE;


--
-- Name: Employee FK_Employee_User_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Employee"
    ADD CONSTRAINT "FK_Employee_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE CASCADE;


--
-- Name: Feedback FK_Feedback_Client_ClientId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Feedback"
    ADD CONSTRAINT "FK_Feedback_Client_ClientId" FOREIGN KEY ("ClientId") REFERENCES public."Client"("Id") ON DELETE CASCADE;


--
-- Name: Feedback FK_Feedback_Employee_SupportId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Feedback"
    ADD CONSTRAINT "FK_Feedback_Employee_SupportId" FOREIGN KEY ("SupportId") REFERENCES public."Employee"("Id") ON DELETE SET NULL;


--
-- Name: Feedback FK_Feedback_Ticket_TicketId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Feedback"
    ADD CONSTRAINT "FK_Feedback_Ticket_TicketId" FOREIGN KEY ("TicketId") REFERENCES public."Ticket"("Id") ON DELETE CASCADE;


--
-- Name: NotificationSettings FK_NotificationSettings_User_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."NotificationSettings"
    ADD CONSTRAINT "FK_NotificationSettings_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE CASCADE;


--
-- Name: Notification FK_Notification_Ticket_TicketId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Notification"
    ADD CONSTRAINT "FK_Notification_Ticket_TicketId" FOREIGN KEY ("TicketId") REFERENCES public."Ticket"("Id") ON DELETE SET NULL;


--
-- Name: Notification FK_Notification_User_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Notification"
    ADD CONSTRAINT "FK_Notification_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE CASCADE;


--
-- Name: PasswordResetToken FK_PasswordResetToken_User_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PasswordResetToken"
    ADD CONSTRAINT "FK_PasswordResetToken_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE CASCADE;


--
-- Name: SearchPreset FK_SearchPreset_User_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SearchPreset"
    ADD CONSTRAINT "FK_SearchPreset_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE CASCADE;


--
-- Name: Solution FK_Solution_Ticket_TicketId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Solution"
    ADD CONSTRAINT "FK_Solution_Ticket_TicketId" FOREIGN KEY ("TicketId") REFERENCES public."Ticket"("Id") ON DELETE CASCADE;


--
-- Name: TicketAttachment FK_TicketAttachment_Ticket_TicketId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TicketAttachment"
    ADD CONSTRAINT "FK_TicketAttachment_Ticket_TicketId" FOREIGN KEY ("TicketId") REFERENCES public."Ticket"("Id") ON DELETE CASCADE;


--
-- Name: TicketAttachment FK_TicketAttachment_User_UploadedByUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TicketAttachment"
    ADD CONSTRAINT "FK_TicketAttachment_User_UploadedByUserId" FOREIGN KEY ("UploadedByUserId") REFERENCES public."User"("Id") ON DELETE RESTRICT;


--
-- Name: TicketComment FK_TicketComment_Ticket_TicketId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TicketComment"
    ADD CONSTRAINT "FK_TicketComment_Ticket_TicketId" FOREIGN KEY ("TicketId") REFERENCES public."Ticket"("Id") ON DELETE CASCADE;


--
-- Name: TicketComment FK_TicketComment_User_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TicketComment"
    ADD CONSTRAINT "FK_TicketComment_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE RESTRICT;


--
-- Name: TicketHistory FK_TicketHistory_Ticket_TicketId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TicketHistory"
    ADD CONSTRAINT "FK_TicketHistory_Ticket_TicketId" FOREIGN KEY ("TicketId") REFERENCES public."Ticket"("Id") ON DELETE CASCADE;


--
-- Name: Ticket FK_Ticket_Client_ClientId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Ticket"
    ADD CONSTRAINT "FK_Ticket_Client_ClientId" FOREIGN KEY ("ClientId") REFERENCES public."Client"("Id") ON DELETE CASCADE;


--
-- Name: Ticket FK_Ticket_Employee_AssigneeEmployeeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Ticket"
    ADD CONSTRAINT "FK_Ticket_Employee_AssigneeEmployeeId" FOREIGN KEY ("AssigneeEmployeeId") REFERENCES public."Employee"("Id") ON DELETE SET NULL;


--
-- Name: UserUiSettings FK_UserUiSettings_User_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserUiSettings"
    ADD CONSTRAINT "FK_UserUiSettings_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 4JU2yXvzcD6begUTiHkBRAH0ivO9IYgT0nWQxevt3CdObmFWbYxRgSTMwCWPQR5

